// Generated by tools/import_fe8_assets.py. Do not hand-edit.
#include "fe8_unit_visuals.h"

#include <stdexcept>
using namespace std;

namespace fe_tiles
{
namespace
{
const vector<UnitVisualInfo> kVisuals = {
    {UnitVisual::ArchMogall, "Arch_Mogall", "graphics/unit_icon/move/unit_icon_move_Arch_Mogall_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Arch_Mogall_sheet.png", "unit_icon_move_Arch_Mogall_motion"},
    {UnitVisual::Archer, "Archer", "graphics/unit_icon/move/unit_icon_move_Archer_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Archer_sheet.png", "unit_icon_move_Archer_motion"},
    {UnitVisual::ArcherF, "Archer_F", "graphics/unit_icon/move/unit_icon_move_Archer_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Archer_F_sheet.png", "unit_icon_move_Archer_F_motion"},
    {UnitVisual::ArmorKnight, "Armor_Knight", "graphics/unit_icon/move/unit_icon_move_Armor_Knight_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Armor_Knight_sheet.png", "unit_icon_move_Armor_Knight_motion"},
    {UnitVisual::Assassin, "Assassin", "graphics/unit_icon/move/unit_icon_move_Assassin_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Assassin_sheet.png", "unit_icon_move_Assassin_motion"},
    {UnitVisual::AssassinF, "Assassin_F", "graphics/unit_icon/move/unit_icon_move_Assassin_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Assassin_F_sheet.png", "unit_icon_move_Assassin_F_motion"},
    {UnitVisual::Bael, "Bael", "graphics/unit_icon/move/unit_icon_move_Bael_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Bael_sheet.png", "unit_icon_move_Bael_motion"},
    {UnitVisual::Bard, "Bard", "graphics/unit_icon/move/unit_icon_move_Bard_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Bard_sheet.png", "unit_icon_move_Bard_motion"},
    {UnitVisual::Berserker, "Berserker", "graphics/unit_icon/move/unit_icon_move_Berserker_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Berserker_sheet.png", "unit_icon_move_Berserker_motion"},
    {UnitVisual::Bishop, "Bishop", "graphics/unit_icon/move/unit_icon_move_Bishop_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Bishop_sheet.png", "unit_icon_move_Bishop_motion"},
    {UnitVisual::BishopF, "Bishop_F", "graphics/unit_icon/move/unit_icon_move_Bishop_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Bishop_F_sheet.png", "unit_icon_move_Bishop_F_motion"},
    {UnitVisual::BlstKillerEmpty, "Blst_Killer_Empty", "graphics/unit_icon/move/unit_icon_move_Blst_Killer_Empty_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Blst_Killer_Empty_sheet.png", "unit_icon_move_Blst_Killer_Empty_motion"},
    {UnitVisual::BlstKillerUsed, "Blst_Killer_Used", "graphics/unit_icon/move/unit_icon_move_Blst_Killer_Used_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Blst_Killer_Used_sheet.png", "unit_icon_move_Blst_Killer_Used_motion"},
    {UnitVisual::BlstLongEmpty, "Blst_Long_Empty", "graphics/unit_icon/move/unit_icon_move_Blst_Long_Empty_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Blst_Long_Empty_sheet.png", "unit_icon_move_Blst_Long_Empty_motion"},
    {UnitVisual::BlstLongUsed, "Blst_Long_Used", "graphics/unit_icon/move/unit_icon_move_Blst_Long_Used_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Blst_Long_Used_sheet.png", "unit_icon_move_Blst_Long_Used_motion"},
    {UnitVisual::BlstRegularUsed, "Blst_Regular_Used", "graphics/unit_icon/move/unit_icon_move_Blst_Regular_Used_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Blst_Regular_Used_sheet.png", "unit_icon_move_Blst_Regular_Used_motion"},
    {UnitVisual::BlstUsedEmpty, "Blst_Used_Empty", "graphics/unit_icon/move/unit_icon_move_Blst_Used_Empty_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Blst_Used_Empty_sheet.png", "unit_icon_move_Blst_Used_Empty_motion"},
    {UnitVisual::Bonewalker, "Bonewalker", "graphics/unit_icon/move/unit_icon_move_Bonewalker_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Bonewalker_sheet.png", "unit_icon_move_Bonewalker_motion"},
    {UnitVisual::BonewalkerBow, "Bonewalker_Bow", "graphics/unit_icon/move/unit_icon_move_Bonewalker_Bow_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Bonewalker_Bow_sheet.png", "unit_icon_move_Bonewalker_Bow_motion"},
    {UnitVisual::Brigand, "Brigand", "graphics/unit_icon/move/unit_icon_move_Brigand_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Brigand_sheet.png", "unit_icon_move_Brigand_motion"},
    {UnitVisual::Cavalier, "Cavalier", "graphics/unit_icon/move/unit_icon_move_Cavalier_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Cavalier_sheet.png", "unit_icon_move_Cavalier_motion"},
    {UnitVisual::CivilianF1, "Civilian_F1", "graphics/unit_icon/move/unit_icon_move_Civilian_F1_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Civilian_F1_sheet.png", "unit_icon_move_Civilian_F1_motion"},
    {UnitVisual::CivilianF2, "Civilian_F2", "graphics/unit_icon/move/unit_icon_move_Civilian_F2_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Civilian_F2_sheet.png", "unit_icon_move_Civilian_F2_motion"},
    {UnitVisual::CivilianM1, "Civilian_M1", "graphics/unit_icon/move/unit_icon_move_Civilian_M1_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Civilian_M1_sheet.png", "unit_icon_move_Civilian_M1_motion"},
    {UnitVisual::CivilianM2, "Civilian_M2", "graphics/unit_icon/move/unit_icon_move_Civilian_M2_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Civilian_M2_sheet.png", "unit_icon_move_Civilian_M2_motion"},
    {UnitVisual::Cleric, "Cleric", "graphics/unit_icon/move/unit_icon_move_Cleric_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Cleric_sheet.png", "unit_icon_move_Cleric_motion"},
    {UnitVisual::Cyclops, "Cyclops", "graphics/unit_icon/move/unit_icon_move_Cyclops_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Cyclops_sheet.png", "unit_icon_move_Cyclops_motion"},
    {UnitVisual::Dancer, "Dancer", "graphics/unit_icon/move/unit_icon_move_Dancer_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Dancer_sheet.png", "unit_icon_move_Dancer_motion"},
    {UnitVisual::Deathgoyle, "Deathgoyle", "graphics/unit_icon/move/unit_icon_move_Deathgoyle_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Deathgoyle_sheet.png", "unit_icon_move_Deathgoyle_motion"},
    {UnitVisual::DemonKing, "Demon_King", "graphics/unit_icon/move/unit_icon_move_Demon_King_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Demon_King_sheet.png", "unit_icon_move_Demon_King_motion"},
    {UnitVisual::DracoZombie, "Draco_Zombie", "graphics/unit_icon/move/unit_icon_move_Draco_Zombie_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Draco_Zombie_sheet.png", "unit_icon_move_Draco_Zombie_motion"},
    {UnitVisual::Druid, "Druid", "graphics/unit_icon/move/unit_icon_move_Druid_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Druid_sheet.png", "unit_icon_move_Druid_motion"},
    {UnitVisual::EirikaLord, "Eirika_Lord", "graphics/unit_icon/move/unit_icon_move_Eirika_Lord_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Eirika_Lord_sheet.png", "unit_icon_move_Eirika_Lord_motion"},
    {UnitVisual::EirikaMasterLord, "Eirika_Master_Lord", "graphics/unit_icon/move/unit_icon_move_Eirika_Master_Lord_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Eirika_Master_Lord_sheet.png", "unit_icon_move_Eirika_Master_Lord_motion"},
    {UnitVisual::ElderBael, "Elder_Bael", "graphics/unit_icon/move/unit_icon_move_Elder_Bael_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Elder_Bael_sheet.png", "unit_icon_move_Elder_Bael_motion"},
    {UnitVisual::Entoumbed, "Entoumbed", "graphics/unit_icon/move/unit_icon_move_Entoumbed_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Entoumbed_sheet.png", "unit_icon_move_Entoumbed_motion"},
    {UnitVisual::EphraimLord, "Ephraim_Lord", "graphics/unit_icon/move/unit_icon_move_Ephraim_Lord_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Ephraim_Lord_sheet.png", "unit_icon_move_Ephraim_Lord_motion"},
    {UnitVisual::EphraimMasterLord, "Ephraim_Master_Lord", "graphics/unit_icon/move/unit_icon_move_Ephraim_Master_Lord_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Ephraim_Master_Lord_sheet.png", "unit_icon_move_Ephraim_Master_Lord_motion"},
    {UnitVisual::FalconKnight, "Falcon_Knight", "graphics/unit_icon/move/unit_icon_move_Falcon_Knight_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Falcon_Knight_sheet.png", "unit_icon_move_Falcon_Knight_motion"},
    {UnitVisual::FallenPeer, "Fallen_Peer", "graphics/unit_icon/move/unit_icon_move_Fallen_Peer_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Fallen_Peer_sheet.png", "unit_icon_move_Fallen_Peer_motion"},
    {UnitVisual::FallenPrince, "Fallen_Prince", "graphics/unit_icon/move/unit_icon_move_Fallen_Prince_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Fallen_Prince_sheet.png", "unit_icon_move_Fallen_Prince_motion"},
    {UnitVisual::Fighter, "Fighter", "graphics/unit_icon/move/unit_icon_move_Fighter_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Fighter_sheet.png", "unit_icon_move_Fighter_motion"},
    {UnitVisual::Fleet, "Fleet", "graphics/unit_icon/move/unit_icon_move_Fleet_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Fleet_sheet.png", "unit_icon_move_Fleet_motion"},
    {UnitVisual::Gargoyle, "Gargoyle", "graphics/unit_icon/move/unit_icon_move_Gargoyle_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Gargoyle_sheet.png", "unit_icon_move_Gargoyle_motion"},
    {UnitVisual::General, "General", "graphics/unit_icon/move/unit_icon_move_General_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_General_sheet.png", "unit_icon_move_General_motion"},
    {UnitVisual::Gorgon, "Gorgon", "graphics/unit_icon/move/unit_icon_move_Gorgon_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Gorgon_sheet.png", "unit_icon_move_Gorgon_motion"},
    {UnitVisual::Gorgonegg, "Gorgonegg", "graphics/unit_icon/move/unit_icon_move_Gorgonegg_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Gorgonegg_sheet.png", "unit_icon_move_Gorgonegg_motion"},
    {UnitVisual::Gorgonegg2, "Gorgonegg2", "graphics/unit_icon/move/unit_icon_move_Gorgonegg2_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Gorgonegg2_sheet.png", "unit_icon_move_Gorgonegg2_motion"},
    {UnitVisual::GreatKnight, "Great_Knight", "graphics/unit_icon/move/unit_icon_move_Great_Knight_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Great_Knight_sheet.png", "unit_icon_move_Great_Knight_motion"},
    {UnitVisual::Gwyllgi, "Gwyllgi", "graphics/unit_icon/move/unit_icon_move_Gwyllgi_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Gwyllgi_sheet.png", "unit_icon_move_Gwyllgi_motion"},
    {UnitVisual::Hero, "Hero", "graphics/unit_icon/move/unit_icon_move_Hero_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Hero_sheet.png", "unit_icon_move_Hero_motion"},
    {UnitVisual::HeroF, "Hero_F", "graphics/unit_icon/move/unit_icon_move_Hero_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Hero_F_sheet.png", "unit_icon_move_Hero_F_motion"},
    {UnitVisual::JourneymanT2, "Journeyman_T2", "graphics/unit_icon/move/unit_icon_move_Journeyman_T2_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Journeyman_T2_sheet.png", "unit_icon_move_Journeyman_T2_motion"},
    {UnitVisual::Maelduin, "Maelduin", "graphics/unit_icon/move/unit_icon_move_Maelduin_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Maelduin_sheet.png", "unit_icon_move_Maelduin_motion"},
    {UnitVisual::Mage, "Mage", "graphics/unit_icon/move/unit_icon_move_Mage_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Mage_sheet.png", "unit_icon_move_Mage_motion"},
    {UnitVisual::MageF, "Mage_F", "graphics/unit_icon/move/unit_icon_move_Mage_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Mage_F_sheet.png", "unit_icon_move_Mage_F_motion"},
    {UnitVisual::MageKnight, "Mage_Knight", "graphics/unit_icon/move/unit_icon_move_Mage_Knight_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Mage_Knight_sheet.png", "unit_icon_move_Mage_Knight_motion"},
    {UnitVisual::MageKnightF, "Mage_Knight_F", "graphics/unit_icon/move/unit_icon_move_Mage_Knight_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Mage_Knight_F_sheet.png", "unit_icon_move_Mage_Knight_F_motion"},
    {UnitVisual::Manakete, "Manakete", "graphics/unit_icon/move/unit_icon_move_Manakete_sheet.png", "", "unit_icon_move_Manakete_motion"},
    {UnitVisual::Manakete2, "Manakete_2", "graphics/unit_icon/move/unit_icon_move_Manakete_2_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Manakete_2_sheet.png", "unit_icon_move_Manakete_2_motion"},
    {UnitVisual::ManaketeMyrrh, "Manakete_Myrrh", "graphics/unit_icon/move/unit_icon_move_Manakete_Myrrh_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Manakete_Myrrh_sheet.png", "unit_icon_move_Manakete_Myrrh_motion"},
    {UnitVisual::Mauthedoog, "Mauthedoog", "graphics/unit_icon/move/unit_icon_move_Mauthedoog_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Mauthedoog_sheet.png", "unit_icon_move_Mauthedoog_motion"},
    {UnitVisual::Mercenary, "Mercenary", "graphics/unit_icon/move/unit_icon_move_Mercenary_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Mercenary_sheet.png", "unit_icon_move_Mercenary_motion"},
    {UnitVisual::MercenaryF, "Mercenary_F", "graphics/unit_icon/move/unit_icon_move_Mercenary_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Mercenary_F_sheet.png", "unit_icon_move_Mercenary_F_motion"},
    {UnitVisual::Mogall, "Mogall", "graphics/unit_icon/move/unit_icon_move_Mogall_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Mogall_sheet.png", "unit_icon_move_Mogall_motion"},
    {UnitVisual::Monk, "Monk", "graphics/unit_icon/move/unit_icon_move_Monk_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Monk_sheet.png", "unit_icon_move_Monk_motion"},
    {UnitVisual::Myrmidon, "Myrmidon", "graphics/unit_icon/move/unit_icon_move_Myrmidon_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Myrmidon_sheet.png", "unit_icon_move_Myrmidon_motion"},
    {UnitVisual::MyrmidonF, "Myrmidon_F", "graphics/unit_icon/move/unit_icon_move_Myrmidon_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Myrmidon_F_sheet.png", "unit_icon_move_Myrmidon_F_motion"},
    {UnitVisual::Necromancer, "Necromancer", "graphics/unit_icon/move/unit_icon_move_Necromancer_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Necromancer_sheet.png", "unit_icon_move_Necromancer_motion"},
    {UnitVisual::Paladin, "Paladin", "graphics/unit_icon/move/unit_icon_move_Paladin_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Paladin_sheet.png", "unit_icon_move_Paladin_motion"},
    {UnitVisual::Peer, "Peer", "graphics/unit_icon/move/unit_icon_move_Peer_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Peer_sheet.png", "unit_icon_move_Peer_motion"},
    {UnitVisual::PegasusKnight, "Pegasus_Knight", "graphics/unit_icon/move/unit_icon_move_Pegasus_Knight_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Pegasus_Knight_sheet.png", "unit_icon_move_Pegasus_Knight_motion"},
    {UnitVisual::Phantom, "Phantom", "graphics/unit_icon/move/unit_icon_move_Phantom_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Phantom_sheet.png", "unit_icon_move_Phantom_motion"},
    {UnitVisual::Pirate, "Pirate", "graphics/unit_icon/move/unit_icon_move_Pirate_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Pirate_sheet.png", "unit_icon_move_Pirate_motion"},
    {UnitVisual::Pontifex, "Pontifex", "graphics/unit_icon/move/unit_icon_move_Pontifex_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Pontifex_sheet.png", "unit_icon_move_Pontifex_motion"},
    {UnitVisual::Priest, "Priest", "graphics/unit_icon/move/unit_icon_move_Priest_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Priest_sheet.png", "unit_icon_move_Priest_motion"},
    {UnitVisual::Prince, "Prince", "graphics/unit_icon/move/unit_icon_move_Prince_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Prince_sheet.png", "unit_icon_move_Prince_motion"},
    {UnitVisual::PupilT2, "Pupil_T2", "graphics/unit_icon/move/unit_icon_move_Pupil_T2_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Pupil_T2_sheet.png", "unit_icon_move_Pupil_T2_motion"},
    {UnitVisual::Queen, "Queen", "graphics/unit_icon/move/unit_icon_move_Queen_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Queen_sheet.png", "unit_icon_move_Queen_motion"},
    {UnitVisual::Queen2, "Queen_2", "graphics/unit_icon/move/unit_icon_move_Queen_2_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Queen_2_sheet.png", "unit_icon_move_Queen_2_motion"},
    {UnitVisual::Ranger, "Ranger", "graphics/unit_icon/move/unit_icon_move_Ranger_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Ranger_sheet.png", "unit_icon_move_Ranger_motion"},
    {UnitVisual::RecruitT1, "Recruit_T1", "graphics/unit_icon/move/unit_icon_move_Recruit_T1_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Recruit_T1_sheet.png", "unit_icon_move_Recruit_T1_motion"},
    {UnitVisual::Revenant, "Revenant", "graphics/unit_icon/move/unit_icon_move_Revenant_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Revenant_sheet.png", "unit_icon_move_Revenant_motion"},
    {UnitVisual::Rogue, "Rogue", "graphics/unit_icon/move/unit_icon_move_Rogue_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Rogue_sheet.png", "unit_icon_move_Rogue_motion"},
    {UnitVisual::Sage, "Sage", "graphics/unit_icon/move/unit_icon_move_Sage_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Sage_sheet.png", "unit_icon_move_Sage_motion"},
    {UnitVisual::SageF, "Sage_F", "graphics/unit_icon/move/unit_icon_move_Sage_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Sage_F_sheet.png", "unit_icon_move_Sage_F_motion"},
    {UnitVisual::Shaman, "Shaman", "graphics/unit_icon/move/unit_icon_move_Shaman_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Shaman_sheet.png", "unit_icon_move_Shaman_motion"},
    {UnitVisual::Sniper, "Sniper", "graphics/unit_icon/move/unit_icon_move_Sniper_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Sniper_sheet.png", "unit_icon_move_Sniper_motion"},
    {UnitVisual::SniperF, "Sniper_F", "graphics/unit_icon/move/unit_icon_move_Sniper_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Sniper_F_sheet.png", "unit_icon_move_Sniper_F_motion"},
    {UnitVisual::Soldier, "Soldier", "graphics/unit_icon/move/unit_icon_move_Soldier_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Soldier_sheet.png", "unit_icon_move_Soldier_motion"},
    {UnitVisual::Summoner, "Summoner", "graphics/unit_icon/move/unit_icon_move_Summoner_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Summoner_sheet.png", "unit_icon_move_Summoner_motion"},
    {UnitVisual::Swordmaster, "Swordmaster", "graphics/unit_icon/move/unit_icon_move_Swordmaster_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Swordmaster_sheet.png", "unit_icon_move_Swordmaster_motion"},
    {UnitVisual::SwordmasterF, "Swordmaster_F", "graphics/unit_icon/move/unit_icon_move_Swordmaster_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Swordmaster_F_sheet.png", "unit_icon_move_Swordmaster_F_motion"},
    {UnitVisual::Tarvos, "Tarvos", "graphics/unit_icon/move/unit_icon_move_Tarvos_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Tarvos_sheet.png", "unit_icon_move_Tarvos_motion"},
    {UnitVisual::Tent, "Tent", "graphics/unit_icon/move/unit_icon_move_Tent_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Tent_sheet.png", "unit_icon_move_Tent_motion"},
    {UnitVisual::Thief, "Thief", "graphics/unit_icon/move/unit_icon_move_Thief_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Thief_sheet.png", "unit_icon_move_Thief_motion"},
    {UnitVisual::Troubadour, "Troubadour", "graphics/unit_icon/move/unit_icon_move_Troubadour_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Troubadour_sheet.png", "unit_icon_move_Troubadour_motion"},
    {UnitVisual::Unk77, "Unk77", "graphics/unit_icon/move/unit_icon_move_Unk77_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Unk77_sheet.png", "unit_icon_move_Unk77_motion"},
    {UnitVisual::Valkyrie, "Valkyrie", "graphics/unit_icon/move/unit_icon_move_Valkyrie_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Valkyrie_sheet.png", "unit_icon_move_Valkyrie_motion"},
    {UnitVisual::Warrior, "Warrior", "graphics/unit_icon/move/unit_icon_move_Warrior_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Warrior_sheet.png", "unit_icon_move_Warrior_motion"},
    {UnitVisual::Wight, "Wight", "graphics/unit_icon/move/unit_icon_move_Wight_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Wight_sheet.png", "unit_icon_move_Wight_motion"},
    {UnitVisual::WightBow, "Wight_Bow", "graphics/unit_icon/move/unit_icon_move_Wight_Bow_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Wight_Bow_sheet.png", "unit_icon_move_Wight_Bow_motion"},
    {UnitVisual::WyvernKnight, "Wyvern_Knight", "graphics/unit_icon/move/unit_icon_move_Wyvern_Knight_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Wyvern_Knight_sheet.png", "unit_icon_move_Wyvern_Knight_motion"},
    {UnitVisual::WyvernKnightF, "Wyvern_Knight_F", "graphics/unit_icon/move/unit_icon_move_Wyvern_Knight_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Wyvern_Knight_F_sheet.png", "unit_icon_move_Wyvern_Knight_F_motion"},
    {UnitVisual::WyvernLord, "Wyvern_Lord", "graphics/unit_icon/move/unit_icon_move_Wyvern_Lord_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Wyvern_Lord_sheet.png", "unit_icon_move_Wyvern_Lord_motion"},
    {UnitVisual::WyvernLordF, "Wyvern_Lord_F", "graphics/unit_icon/move/unit_icon_move_Wyvern_Lord_F_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Wyvern_Lord_F_sheet.png", "unit_icon_move_Wyvern_Lord_F_motion"},
    {UnitVisual::WyvernRider, "Wyvern_Rider", "graphics/unit_icon/move/unit_icon_move_Wyvern_Rider_sheet.png", "graphics/unit_icon/wait/unit_icon_wait_Wyvern_Rider_sheet.png", "unit_icon_move_Wyvern_Rider_motion"}
};

const vector<MapUnitMotionProgram> kMotionPrograms = {
    {UnitVisual::ArchMogall, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::ArchMogall, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::ArchMogall, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::ArchMogall, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::ArchMogall, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Archer, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Archer, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Archer, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Archer, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Archer, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::ArcherF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::ArcherF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::ArcherF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::ArcherF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::ArcherF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::ArmorKnight, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::ArmorKnight, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::ArmorKnight, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::ArmorKnight, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::ArmorKnight, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Assassin, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Assassin, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Assassin, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Assassin, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Assassin, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::AssassinF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::AssassinF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::AssassinF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::AssassinF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::AssassinF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Bael, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Bael, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Bael, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Bael, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Bael, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Bard, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Bard, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Bard, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Bard, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Bard, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Bard, 5, "action_5", {{6, 17}, {15, 18}, {3, 17}, {11, 16}, {5, 17}, {11, 18}, {0, 0}}},
    {UnitVisual::Berserker, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Berserker, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Berserker, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Berserker, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Berserker, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Bishop, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Bishop, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Bishop, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Bishop, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Bishop, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::BishopF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::BishopF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::BishopF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::BishopF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::BishopF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::BlstKillerEmpty, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::BlstKillerEmpty, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::BlstKillerEmpty, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::BlstKillerEmpty, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::BlstKillerEmpty, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::BlstKillerUsed, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::BlstKillerUsed, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::BlstKillerUsed, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::BlstKillerUsed, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::BlstKillerUsed, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::BlstLongEmpty, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::BlstLongEmpty, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::BlstLongEmpty, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::BlstLongEmpty, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::BlstLongEmpty, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::BlstLongUsed, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::BlstLongUsed, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::BlstLongUsed, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::BlstLongUsed, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::BlstLongUsed, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::BlstRegularUsed, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::BlstRegularUsed, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::BlstRegularUsed, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::BlstRegularUsed, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::BlstRegularUsed, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::BlstUsedEmpty, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::BlstUsedEmpty, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::BlstUsedEmpty, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::BlstUsedEmpty, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::BlstUsedEmpty, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Bonewalker, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Bonewalker, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Bonewalker, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Bonewalker, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Bonewalker, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::BonewalkerBow, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::BonewalkerBow, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::BonewalkerBow, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::BonewalkerBow, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::BonewalkerBow, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Brigand, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Brigand, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Brigand, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Brigand, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Brigand, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Cavalier, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Cavalier, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Cavalier, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Cavalier, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Cavalier, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::CivilianF1, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::CivilianF1, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::CivilianF1, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::CivilianF1, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::CivilianF1, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::CivilianF2, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::CivilianF2, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::CivilianF2, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::CivilianF2, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::CivilianF2, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::CivilianM1, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::CivilianM1, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::CivilianM1, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::CivilianM1, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::CivilianM1, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::CivilianM2, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::CivilianM2, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::CivilianM2, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::CivilianM2, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::CivilianM2, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Cleric, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Cleric, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Cleric, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Cleric, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Cleric, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Cyclops, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Cyclops, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Cyclops, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Cyclops, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Cyclops, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Dancer, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Dancer, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Dancer, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Dancer, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Dancer, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Dancer, 5, "action_5", {{5, 0}, {3, 12}, {2, 14}, {3, 5}, {2, 7}, {3, 8}, {2, 9}, {3, 20}, {15, 19}, {3, 20}, {1, 21}, {0, 0}}},
    {UnitVisual::Dancer, 6, "action_6", {{5, 0}, {3, 12}, {2, 14}, {3, 5}, {2, 7}, {3, 8}, {2, 9}, {3, 20}, {1, 19}, {0, 0}}},
    {UnitVisual::Deathgoyle, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Deathgoyle, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Deathgoyle, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Deathgoyle, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Deathgoyle, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::DemonKing, 0, "left", {{16, 0}, {10, 1}, {16, 2}, {10, 3}}},
    {UnitVisual::DemonKing, 1, "right", {{16, 4}, {10, 5}, {16, 6}, {10, 7}}},
    {UnitVisual::DemonKing, 2, "down", {{16, 8}, {10, 9}, {16, 10}, {10, 11}}},
    {UnitVisual::DemonKing, 3, "up", {{16, 12}, {10, 13}, {16, 14}, {10, 15}}},
    {UnitVisual::DemonKing, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::DracoZombie, 0, "left", {{18, 0}, {10, 1}, {18, 2}, {10, 3}}},
    {UnitVisual::DracoZombie, 1, "right", {{18, 4}, {10, 5}, {18, 6}, {10, 7}}},
    {UnitVisual::DracoZombie, 2, "down", {{18, 8}, {10, 9}, {18, 10}, {10, 11}}},
    {UnitVisual::DracoZombie, 3, "up", {{18, 12}, {10, 13}, {18, 14}, {10, 15}}},
    {UnitVisual::DracoZombie, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Druid, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Druid, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Druid, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Druid, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Druid, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::EirikaLord, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::EirikaLord, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::EirikaLord, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::EirikaLord, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::EirikaLord, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::EirikaMasterLord, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::EirikaMasterLord, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::EirikaMasterLord, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::EirikaMasterLord, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::EirikaMasterLord, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::ElderBael, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::ElderBael, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::ElderBael, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::ElderBael, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::ElderBael, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Entoumbed, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Entoumbed, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Entoumbed, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Entoumbed, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Entoumbed, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::EphraimLord, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::EphraimLord, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::EphraimLord, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::EphraimLord, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::EphraimLord, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::EphraimMasterLord, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::EphraimMasterLord, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::EphraimMasterLord, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::EphraimMasterLord, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::EphraimMasterLord, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::FalconKnight, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::FalconKnight, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::FalconKnight, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::FalconKnight, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::FalconKnight, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::FallenPeer, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::FallenPeer, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::FallenPeer, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::FallenPeer, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::FallenPeer, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::FallenPrince, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::FallenPrince, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::FallenPrince, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::FallenPrince, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::FallenPrince, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Fighter, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Fighter, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Fighter, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Fighter, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Fighter, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Fleet, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Fleet, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Fleet, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Fleet, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Fleet, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Gargoyle, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Gargoyle, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Gargoyle, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Gargoyle, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Gargoyle, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::General, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::General, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::General, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::General, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::General, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Gorgon, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Gorgon, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Gorgon, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Gorgon, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Gorgon, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Gorgonegg, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Gorgonegg, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Gorgonegg, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Gorgonegg, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Gorgonegg, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Gorgonegg2, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Gorgonegg2, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Gorgonegg2, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Gorgonegg2, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Gorgonegg2, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::GreatKnight, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::GreatKnight, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::GreatKnight, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::GreatKnight, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::GreatKnight, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Gwyllgi, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Gwyllgi, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Gwyllgi, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Gwyllgi, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Gwyllgi, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Hero, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Hero, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Hero, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Hero, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Hero, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::HeroF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::HeroF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::HeroF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::HeroF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::HeroF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::JourneymanT2, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::JourneymanT2, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::JourneymanT2, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::JourneymanT2, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::JourneymanT2, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Maelduin, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Maelduin, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Maelduin, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Maelduin, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Maelduin, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Mage, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Mage, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Mage, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Mage, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Mage, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::MageF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::MageF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::MageF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::MageF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::MageF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::MageKnight, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::MageKnight, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::MageKnight, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::MageKnight, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::MageKnight, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::MageKnightF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::MageKnightF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::MageKnightF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::MageKnightF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::MageKnightF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Manakete, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Manakete, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Manakete, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Manakete, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Manakete, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Manakete2, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Manakete2, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Manakete2, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Manakete2, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Manakete2, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::ManaketeMyrrh, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::ManaketeMyrrh, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::ManaketeMyrrh, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::ManaketeMyrrh, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::ManaketeMyrrh, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Mauthedoog, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Mauthedoog, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Mauthedoog, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Mauthedoog, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Mauthedoog, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Mercenary, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Mercenary, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Mercenary, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Mercenary, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Mercenary, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::MercenaryF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::MercenaryF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::MercenaryF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::MercenaryF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::MercenaryF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Mogall, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Mogall, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Mogall, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Mogall, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Mogall, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Monk, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Monk, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Monk, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Monk, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Monk, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Myrmidon, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Myrmidon, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Myrmidon, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Myrmidon, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Myrmidon, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::MyrmidonF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::MyrmidonF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::MyrmidonF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::MyrmidonF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::MyrmidonF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Necromancer, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Necromancer, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Necromancer, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Necromancer, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Necromancer, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Paladin, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Paladin, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Paladin, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Paladin, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Paladin, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Peer, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Peer, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Peer, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Peer, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Peer, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::PegasusKnight, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::PegasusKnight, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::PegasusKnight, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::PegasusKnight, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::PegasusKnight, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Phantom, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Phantom, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Phantom, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Phantom, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Phantom, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Pirate, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Pirate, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Pirate, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Pirate, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Pirate, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Pontifex, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Pontifex, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Pontifex, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Pontifex, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Pontifex, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Priest, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Priest, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Priest, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Priest, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Priest, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Prince, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Prince, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Prince, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Prince, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Prince, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::PupilT2, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::PupilT2, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::PupilT2, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::PupilT2, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::PupilT2, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Queen, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Queen, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Queen, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Queen, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Queen, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Queen2, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Queen2, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Queen2, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Queen2, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Queen2, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Ranger, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Ranger, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Ranger, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Ranger, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Ranger, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::RecruitT1, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::RecruitT1, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::RecruitT1, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::RecruitT1, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::RecruitT1, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Revenant, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Revenant, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Revenant, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Revenant, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Revenant, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Rogue, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Rogue, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Rogue, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Rogue, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Rogue, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Sage, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Sage, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Sage, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Sage, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Sage, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::SageF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::SageF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::SageF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::SageF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::SageF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Shaman, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Shaman, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Shaman, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Shaman, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Shaman, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Sniper, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Sniper, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Sniper, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Sniper, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Sniper, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::SniperF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::SniperF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::SniperF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::SniperF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::SniperF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Soldier, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Soldier, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Soldier, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Soldier, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Soldier, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Summoner, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Summoner, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Summoner, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Summoner, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Summoner, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Swordmaster, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Swordmaster, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Swordmaster, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Swordmaster, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Swordmaster, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::SwordmasterF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::SwordmasterF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::SwordmasterF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::SwordmasterF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::SwordmasterF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Tarvos, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Tarvos, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Tarvos, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Tarvos, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Tarvos, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Tent, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Tent, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Tent, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Tent, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Tent, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Thief, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Thief, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Thief, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Thief, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Thief, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Troubadour, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Troubadour, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Troubadour, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Troubadour, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Troubadour, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Unk77, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Unk77, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Unk77, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Unk77, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Unk77, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Valkyrie, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Valkyrie, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Valkyrie, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Valkyrie, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Valkyrie, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Warrior, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Warrior, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Warrior, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Warrior, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Warrior, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::Wight, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::Wight, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::Wight, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::Wight, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::Wight, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::WightBow, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::WightBow, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::WightBow, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::WightBow, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::WightBow, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::WyvernKnight, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::WyvernKnight, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::WyvernKnight, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::WyvernKnight, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::WyvernKnight, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::WyvernKnightF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::WyvernKnightF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::WyvernKnightF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::WyvernKnightF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::WyvernKnightF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::WyvernLord, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::WyvernLord, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::WyvernLord, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::WyvernLord, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::WyvernLord, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::WyvernLordF, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::WyvernLordF, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::WyvernLordF, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::WyvernLordF, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::WyvernLordF, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}},
    {UnitVisual::WyvernRider, 0, "left", {{13, 0}, {6, 1}, {13, 2}, {6, 3}}},
    {UnitVisual::WyvernRider, 1, "right", {{13, 4}, {6, 5}, {13, 6}, {6, 7}}},
    {UnitVisual::WyvernRider, 2, "down", {{13, 8}, {6, 9}, {13, 10}, {6, 11}}},
    {UnitVisual::WyvernRider, 3, "up", {{13, 12}, {6, 13}, {13, 14}, {6, 15}}},
    {UnitVisual::WyvernRider, 4, "selected", {{20, 16}, {4, 17}, {20, 18}, {4, 17}}}
};
}

const UnitVisualInfo& unit_visual_info(UnitVisual visual)
{
    const int index = static_cast<int>(visual);
    if (index < 0 || index >= static_cast<int>(kVisuals.size()))
    {
        throw out_of_range("Unknown FE8 UnitVisual.");
    }
    return kVisuals[static_cast<size_t>(index)];
}

const vector<UnitVisualInfo>& all_unit_visuals()
{
    return kVisuals;
}

optional<UnitVisual> unit_visual_for_class(int fe8_class_id)
{
    switch (fe8_class_id)
    {
        case 1: return UnitVisual::EphraimLord;
        case 2: return UnitVisual::EirikaLord;
        case 3: return UnitVisual::EphraimMasterLord;
        case 4: return UnitVisual::EirikaMasterLord;
        case 5: return UnitVisual::Cavalier;
        case 6: return UnitVisual::Cavalier;
        case 7: return UnitVisual::Paladin;
        case 8: return UnitVisual::Paladin;
        case 9: return UnitVisual::ArmorKnight;
        case 10: return UnitVisual::ArmorKnight;
        case 11: return UnitVisual::General;
        case 12: return UnitVisual::General;
        case 13: return UnitVisual::Thief;
        case 14: return UnitVisual::Manakete;
        case 15: return UnitVisual::Mercenary;
        case 16: return UnitVisual::MercenaryF;
        case 17: return UnitVisual::Hero;
        case 18: return UnitVisual::HeroF;
        case 19: return UnitVisual::Myrmidon;
        case 20: return UnitVisual::MyrmidonF;
        case 21: return UnitVisual::Swordmaster;
        case 22: return UnitVisual::SwordmasterF;
        case 23: return UnitVisual::Assassin;
        case 24: return UnitVisual::AssassinF;
        case 25: return UnitVisual::Archer;
        case 26: return UnitVisual::ArcherF;
        case 27: return UnitVisual::Sniper;
        case 28: return UnitVisual::SniperF;
        case 29: return UnitVisual::Ranger;
        case 30: return UnitVisual::Ranger;
        case 31: return UnitVisual::WyvernRider;
        case 32: return UnitVisual::WyvernLord;
        case 33: return UnitVisual::WyvernLordF;
        case 34: return UnitVisual::WyvernKnight;
        case 35: return UnitVisual::WyvernKnightF;
        case 36: return UnitVisual::WyvernKnightF;
        case 37: return UnitVisual::Mage;
        case 38: return UnitVisual::MageF;
        case 39: return UnitVisual::Sage;
        case 40: return UnitVisual::SageF;
        case 41: return UnitVisual::MageKnight;
        case 42: return UnitVisual::MageKnightF;
        case 43: return UnitVisual::Bishop;
        case 44: return UnitVisual::BishopF;
        case 45: return UnitVisual::Shaman;
        case 46: return UnitVisual::Shaman;
        case 47: return UnitVisual::Druid;
        case 48: return UnitVisual::Druid;
        case 49: return UnitVisual::Summoner;
        case 50: return UnitVisual::Summoner;
        case 51: return UnitVisual::Rogue;
        case 52: return UnitVisual::Gorgonegg2;
        case 53: return UnitVisual::GreatKnight;
        case 54: return UnitVisual::GreatKnight;
        case 55: return UnitVisual::RecruitT1;
        case 56: return UnitVisual::JourneymanT2;
        case 57: return UnitVisual::PupilT2;
        case 58: return UnitVisual::RecruitT1;
        case 59: return UnitVisual::Manakete2;
        case 60: return UnitVisual::ManaketeMyrrh;
        case 61: return UnitVisual::JourneymanT2;
        case 62: return UnitVisual::PupilT2;
        case 63: return UnitVisual::Fighter;
        case 64: return UnitVisual::Warrior;
        case 65: return UnitVisual::Brigand;
        case 66: return UnitVisual::Pirate;
        case 67: return UnitVisual::Berserker;
        case 68: return UnitVisual::Monk;
        case 69: return UnitVisual::Priest;
        case 70: return UnitVisual::Bard;
        case 71: return UnitVisual::RecruitT1;
        case 72: return UnitVisual::PegasusKnight;
        case 73: return UnitVisual::FalconKnight;
        case 74: return UnitVisual::Cleric;
        case 75: return UnitVisual::Troubadour;
        case 76: return UnitVisual::Valkyrie;
        case 77: return UnitVisual::Dancer;
        case 78: return UnitVisual::Soldier;
        case 79: return UnitVisual::Necromancer;
        case 80: return UnitVisual::Fleet;
        case 81: return UnitVisual::Phantom;
        case 82: return UnitVisual::Revenant;
        case 83: return UnitVisual::Entoumbed;
        case 84: return UnitVisual::Bonewalker;
        case 85: return UnitVisual::BonewalkerBow;
        case 86: return UnitVisual::Wight;
        case 87: return UnitVisual::WightBow;
        case 88: return UnitVisual::Bael;
        case 89: return UnitVisual::ElderBael;
        case 90: return UnitVisual::Cyclops;
        case 91: return UnitVisual::Mauthedoog;
        case 92: return UnitVisual::Gwyllgi;
        case 93: return UnitVisual::Tarvos;
        case 94: return UnitVisual::Maelduin;
        case 95: return UnitVisual::Mogall;
        case 96: return UnitVisual::ArchMogall;
        case 97: return UnitVisual::Gorgon;
        case 98: return UnitVisual::Gorgonegg;
        case 99: return UnitVisual::Gargoyle;
        case 100: return UnitVisual::Deathgoyle;
        case 101: return UnitVisual::DracoZombie;
        case 102: return UnitVisual::DemonKing;
        case 103: return UnitVisual::BlstRegularUsed;
        case 104: return UnitVisual::BlstLongUsed;
        case 105: return UnitVisual::BlstKillerUsed;
        case 106: return UnitVisual::BlstLongEmpty;
        case 107: return UnitVisual::BlstUsedEmpty;
        case 108: return UnitVisual::BlstKillerEmpty;
        case 109: return UnitVisual::CivilianM1;
        case 110: return UnitVisual::CivilianF1;
        case 111: return UnitVisual::CivilianM2;
        case 112: return UnitVisual::CivilianF2;
        case 113: return UnitVisual::CivilianM2;
        case 114: return UnitVisual::CivilianF2;
        case 115: return UnitVisual::Peer;
        case 116: return UnitVisual::Queen;
        case 117: return UnitVisual::Prince;
        case 118: return UnitVisual::Queen2;
        case 119: return UnitVisual::Unk77;
        case 120: return UnitVisual::FallenPrince;
        case 121: return UnitVisual::Tent;
        case 122: return UnitVisual::Pontifex;
        case 123: return UnitVisual::FallenPeer;
        case 124: return UnitVisual::Cyclops;
        case 125: return UnitVisual::ElderBael;
        case 126: return UnitVisual::JourneymanT2;
        case 127: return UnitVisual::PupilT2;
        default: return nullopt;
    }
}

const vector<MapUnitMotionProgram>& all_map_unit_motion_programs()
{
    return kMotionPrograms;
}

const MapUnitMotionProgram* map_unit_motion_program(UnitVisual visual,
                                                    int animation_id)
{
    for (const MapUnitMotionProgram& program : kMotionPrograms)
    {
        if (program.visual == visual && program.animation_id == animation_id)
        {
            return &program;
        }
    }
    return nullptr;
}
}
