// Generated by tools/import_fe8_assets.py. Do not hand-edit.
#pragma once

#include <cstddef>
#include <optional>
#include <string_view>
#include <vector>
using namespace std;

namespace fe_tiles
{
// Every literal FE8 map-unit movement-sheet variant present in this bundle.
// A visual is art, not a gameplay class: several classes can share one sheet.
enum class UnitVisual : int
{
    ArchMogall = 0,
    Archer = 1,
    ArcherF = 2,
    ArmorKnight = 3,
    Assassin = 4,
    AssassinF = 5,
    Bael = 6,
    Bard = 7,
    Berserker = 8,
    Bishop = 9,
    BishopF = 10,
    BlstKillerEmpty = 11,
    BlstKillerUsed = 12,
    BlstLongEmpty = 13,
    BlstLongUsed = 14,
    BlstRegularUsed = 15,
    BlstUsedEmpty = 16,
    Bonewalker = 17,
    BonewalkerBow = 18,
    Brigand = 19,
    Cavalier = 20,
    CivilianF1 = 21,
    CivilianF2 = 22,
    CivilianM1 = 23,
    CivilianM2 = 24,
    Cleric = 25,
    Cyclops = 26,
    Dancer = 27,
    Deathgoyle = 28,
    DemonKing = 29,
    DracoZombie = 30,
    Druid = 31,
    EirikaLord = 32,
    EirikaMasterLord = 33,
    ElderBael = 34,
    Entoumbed = 35,
    EphraimLord = 36,
    EphraimMasterLord = 37,
    FalconKnight = 38,
    FallenPeer = 39,
    FallenPrince = 40,
    Fighter = 41,
    Fleet = 42,
    Gargoyle = 43,
    General = 44,
    Gorgon = 45,
    Gorgonegg = 46,
    Gorgonegg2 = 47,
    GreatKnight = 48,
    Gwyllgi = 49,
    Hero = 50,
    HeroF = 51,
    JourneymanT2 = 52,
    Maelduin = 53,
    Mage = 54,
    MageF = 55,
    MageKnight = 56,
    MageKnightF = 57,
    Manakete = 58,
    Manakete2 = 59,
    ManaketeMyrrh = 60,
    Mauthedoog = 61,
    Mercenary = 62,
    MercenaryF = 63,
    Mogall = 64,
    Monk = 65,
    Myrmidon = 66,
    MyrmidonF = 67,
    Necromancer = 68,
    Paladin = 69,
    Peer = 70,
    PegasusKnight = 71,
    Phantom = 72,
    Pirate = 73,
    Pontifex = 74,
    Priest = 75,
    Prince = 76,
    PupilT2 = 77,
    Queen = 78,
    Queen2 = 79,
    Ranger = 80,
    RecruitT1 = 81,
    Revenant = 82,
    Rogue = 83,
    Sage = 84,
    SageF = 85,
    Shaman = 86,
    Sniper = 87,
    SniperF = 88,
    Soldier = 89,
    Summoner = 90,
    Swordmaster = 91,
    SwordmasterF = 92,
    Tarvos = 93,
    Tent = 94,
    Thief = 95,
    Troubadour = 96,
    Unk77 = 97,
    Valkyrie = 98,
    Warrior = 99,
    Wight = 100,
    WightBow = 101,
    WyvernKnight = 102,
    WyvernKnightF = 103,
    WyvernLord = 104,
    WyvernLordF = 105,
    WyvernRider = 106,
    Count,

    // Compatibility alias used by the original three-unit monitor proof.
    Eirika = EirikaLord,
};

struct UnitVisualInfo
{
    UnitVisual visual;
    string_view key;
    string_view move_png; // relative to assets/fe8/
    string_view wait_png; // relative to assets/fe8/; may be empty
    string_view source_motion_symbol;
};

// Literal AP timing program from FE8's const_data_unit_icon_move.s.
// IDs 0..4 are left/right/down/up/selected; a few visuals add actions.
struct MapUnitMotionStep
{
    int ticks;
    int frame;
};

struct MapUnitMotionProgram
{
    UnitVisual visual;
    int animation_id;
    string_view name;
    vector<MapUnitMotionStep> steps;
};

const UnitVisualInfo& unit_visual_info(UnitVisual visual);
const vector<UnitVisualInfo>& all_unit_visuals();
optional<UnitVisual> unit_visual_for_class(int fe8_class_id);
const vector<MapUnitMotionProgram>& all_map_unit_motion_programs();
const MapUnitMotionProgram* map_unit_motion_program(UnitVisual visual,
                                                    int animation_id);
}
