#pragma once

#include <array>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "map_tile_library.h"
#include "occupancy_overlay.h"

// These are Ashu's sandbox types and algorithms. This bridge deliberately
// owns no duplicate pathfinding, attack-range, prompt, or combat rules.
#include "entity_data.h"
#include "entity_registry.h"
#include "mechanics.h"
#include "pathfinder.h"
using namespace std;

namespace fe_tiles
{
struct BattleResolution
{
    int attacker_id = 0;
    int defender_id = 0;
    string attacker_name;
    string defender_name;
    int attacker_hp_before = 0;
    int attacker_hp_after = 0;
    int attacker_hp_max = 0;
    int defender_hp_before = 0;
    int defender_hp_after = 0;
    int defender_hp_max = 0;
    bool attacker_defeated = false;
    bool defender_defeated = false;
};

// Adapter between the visual workbench and the existing sandbox logic.
//
// It intentionally rebuilds Mapmaker from live Entity locations before every
// gameplay query. Mapmaker's occupancy grid is private, but the Entities,
// Guilds, and terrain vector are already its complete authoritative input.
// Thus the workbench can use the real logic without exposing or changing any
// private state in the sandbox itself.
class SandboxLogicBridge
{
public:
    explicit SandboxLogicBridge(IntGrid terrain);

    // A visual test roster constructed with the same entity factories,
    // movement types, guild assignment, weapons, and Entity fields as the
    // sandbox's Chapter 1 setup. The caller controls the coordinates.
    void create_chapter_one_roster(const array<Cell, 4>& locations);

    // Tile-library visual classes are not sandbox terrain IDs. This makes the
    // one-way mapping that supplies Mapmaker's native FE8 terrain vocabulary.
    static IntGrid gameplay_terrain_from_visual_classes(const IntGrid& classes);
    void set_terrain(IntGrid terrain);

    const IntGrid& terrain() const;
    vector<Entity*> units() const;
    Entity& unit(int entity_id);
    const Entity& unit(int entity_id) const;

    // Exact current sandbox queries. inspect() runs Mapmaker::path_trace and
    // Mapmaker::attack_range; movement() is the landable (not merely traversed)
    // portion from Mapmaker::consider_occupancy.
    void inspect(int entity_id);
    int selected_entity_id() const;
    const IntGrid& movement() const;
    const IntGrid& attack() const;

    // Reconstructs the exact route from the movement state grid generated by
    // Mapmaker::path_trace. No Dijkstra/BFS or terrain rule lives here.
    vector<Cell> route_to(int entity_id, Cell destination) const;

    // Computes the post-move, standing-only attack picture and uses the
    // sandbox's Mapmaker::prompt_attack to expose legal enemy/weapon choices.
    // It is a non-mutating preview; call commit_move only after the renderer
    // finishes traversing route_to().
    void preview_arrival(int entity_id, Cell destination);
    const IntGrid& standing_attack() const;
    const vector<avl_for_atk>& available_attacks() const;

    // Commits an already validated/animated destination to Entity state,
    // rebuilds Mapmaker occupancy from the live entities, and prepares later
    // prompt_attack/battle calls. It contains no movement-rule calculation.
    void commit_move(int entity_id, Cell destination);
    void wait(int entity_id);

    // Checks the exact prompt returned by Mapmaker::prompt_attack, equips that
    // offered inventory slot, then invokes the sandbox's real battle().
    BattleResolution attack(int attacker_id, Cell defender, int inventory_slot);

    // Renderer helper: invoke after CombatPresentation's lunge completes to
    // recreate the occupancy grid from the results of the real battle().
    void rebuild_mapmaker();

    // Useful while this is a player-driven workbench rather than the full
    // Environment phase loop.
    void ready_guild(int guild_id);

private:
    IntGrid terrain_;
    Registry registry_;
    array<Guild, 2> guilds_;
    array<Entity*, 4> units_{};
    unique_ptr<Mapmaker> board_;

    int selected_entity_id_ = 0;
    IntGrid movement_;
    IntGrid attack_;
    IntGrid standing_attack_;
    vector<avl_for_atk> available_attacks_;

    Entity* find_unit(int entity_id) const;
    Entity* find_unit_at(Cell location) const;
    void clear_preview();
    void require_rectangular(const IntGrid& terrain) const;
    IntGrid make_weapon_attack_grid(const Entity& unit, const Weapon& weapon) const;
    IntGrid make_standing_attack_grid(const Entity& unit) const;
};
}
